<a href="https://colab.research.google.com/github/suraj-malhotra/solid-design/blob/master/Column_Transformer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer#missing value
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [3]:
df = pd.read_csv('covid_toy.csv')

In [15]:
df.shape

(100, 6)

In [6]:
df['cough'].value_counts()#gender cough city = categorical columns

Mild      62
Strong    38
Name: cough, dtype: int64

In [8]:
df['city'].value_counts()#gender and city nominal categorical columns

Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: city, dtype: int64

In [9]:
df.isnull().sum()#missing value=fever #gender $ city=onehot encording ,fever=simple imputer ,cough=ordinal encorder

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2) #drop the has covid column in x_train and but not for y_train

In [12]:
X_train   #'has_covid' not present #80$ train data and 20% test data

age  gender  fever   cough       city
75    5    Male  102.0    Mild    Kolkata
57   49  Female   99.0  Strong  Bangalore
49   44    Male  104.0    Mild     Mumbai
52   47  Female  100.0  Strong  Bangalore
88    5  Female  100.0    Mild    Kolkata
..  ...     ...    ...     ...        ...
33   26  Female   98.0    Mild    Kolkata
54   60  Female   99.0    Mild     Mumbai
58   23    Male   98.0  Strong     Mumbai
50   19    Male  101.0    Mild      Delhi
86   25    Male  104.0    Mild  Bangalore

[80 rows x 5 columns]

bad method


In [16]:
# adding simple imputer to fever col #fill missing value in fever by simpleimputer
si = SimpleImputer() #class and si=object
X_train_fever = si.fit_transform(X_train[['fever']]) #only fever column

# also the test data
X_test_fever = si.fit_transform(X_test[['fever']])
                                 
X_train_fever   #all missing value transform into mean value

array([[102.        ],
       [ 99.        ],
       [104.        ],
       [100.        ],
       [100.        ],
       [ 98.        ],
       [103.        ],
       [101.11428571],
       [101.11428571],
       [ 98.        ],
       [ 98.        ],
       [101.        ],
       [103.        ],
       [ 98.        ],
       [103.        ],
       [102.        ],
       [104.        ],
       [101.        ],
       [102.        ],
       [ 98.        ],
       [101.        ],
       [ 99.        ],
       [101.11428571],
       [ 99.        ],
       [100.        ],
       [104.        ],
       [102.        ],
       [ 99.        ],
       [103.        ],
       [103.        ],
       [101.11428571],
       [102.        ],
       [101.        ],
       [104.        ],
       [101.        ],
       [ 98.        ],
       [101.        ],
       [101.        ],
       [102.        ],
       [101.        ],
       [ 99.        ],
       [ 99.        ],
       [ 98.        ],
       [101

In [17]:
# Ordinalencoding -> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']]) # mild small value and strong high value
X_train_cough = oe.fit_transform(X_train[['cough']])

# also the test data
X_test_cough = oe.fit_transform(X_test[['cough']])

X_train_cough

array([[0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],

In [18]:
# OneHotEncoding -> gender,city #gender= 2 categories and city = 4 categories
ohe = OneHotEncoder(drop='first',sparse=False)#for multicollinearity we remove first columns from each and we get 1 columns from gender and 3 columns from city
X_train_gender_city = ohe.fit_transform(X_train[['gender','city']])

# also the test data
X_test_gender_city = ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city

array([[1., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 1., 0.],
       [1., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 0., 0., 1.],
       [1., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [1., 1., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 1., 0.],


In [21]:
# Extracting Age
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values

# also the test data
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age

array([[ 5],
       [49],
       [44],
       [47],
       [ 5],
       [ 5],
       [48],
       [42],
       [38],
       [69],
       [73],
       [14],
       [50],
       [24],
       [60],
       [82],
       [12],
       [64],
       [33],
       [64],
       [65],
       [14],
       [75],
       [65],
       [27],
       [42],
       [20],
       [25],
       [69],
       [16],
       [34],
       [74],
       [38],
       [34],
       [51],
       [83],
       [15],
       [42],
       [24],
       [83],
       [59],
       [66],
       [65],
       [20],
       [84],
       [51],
       [27],
       [72],
       [18],
       [54],
       [47],
       [82],
       [65],
       [46],
       [56],
       [11],
       [12],
       [71],
       [75],
       [23],
       [71],
       [51],
       [17],
       [83],
       [19],
       [79],
       [34],
       [68],
       [16],
       [64],
       [10],
       [ 6],
       [82],
       [73],
       [49],
       [26],
       [60],

In [22]:
X_train_transformed = np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
# also the test data
X_test_transformed = np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed

array([[  5.        , 102.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 49.        ,  99.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 44.        , 104.        ,   1.        ,   0.        ,
          0.        ,   1.        ,   0.        ],
       [ 47.        , 100.        ,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [  5.        , 100.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [  5.        ,  98.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   1.        ],
       [ 48.        , 103.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   0.        ],
       [ 42.        , 101.11428571,   0.        ,   0.        ,
          0.        ,   0.        ,   1.        ],
       [ 38.        , 101.11428571,   1.        ,   1.        ,
          0.    

best method


In [23]:
from sklearn.compose import ColumnTransformer

In [24]:
transformer = ColumnTransformer(transformers=[    #transformer pass in tuple
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(sparse=False,drop='first'),['gender','city'])
],remainder='passthrough')

In [26]:
transformer.fit_transform(X_train)

array([[102.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  49.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  44.        ],
       [100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  47.        ],
       [100.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   5.        ],
       [ 98.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,   5.        ],
       [103.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  48.        ],
       [101.11428571,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  42.        ],
       [101.11428571,   0.        ,   1.        ,   1.        ,
          0.    